
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iskandar
 */
public class login extends javax.swing.JFrame {

  // membuat opsi login
  private static final String ID = "admin";
  private static final String Sandi = "admin123";
  private static boolean konfirmasi;
  
  /**
   * Creates new form login
   */
  public login() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    tf1 = new javax.swing.JTextField();
    jToggleButton1 = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    tf2 = new javax.swing.JPasswordField();
    jLabel4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login Form");

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 0, 0));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("FORM LOGIN");

    jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jLabel2.setText("NAMA ");

    jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jLabel3.setText("PASSWORD");

    tf1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

    jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jToggleButton1.setText("LOGIN");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton1ActionPerformed(evt);
      }
    });

    jToggleButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jToggleButton2.setText("CANCEL");
    jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton2ActionPerformed(evt);
      }
    });

    tf2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

    jLabel4.setText("Username : \"admin\" ; Password : \"admin123\"");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGap(82, 82, 82)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addComponent(jLabel2)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(tf2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
            .addComponent(tf1, javax.swing.GroupLayout.Alignment.LEADING)))
        .addContainerGap(82, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel4)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel2)
        .addGap(1, 1, 1)
        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jToggleButton1)
          .addComponent(jToggleButton2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        .addComponent(jLabel4))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
  doLogin();    // TODO add your handling code here:
  this.dispose();
  }//GEN-LAST:event_jToggleButton1ActionPerformed

  private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
  this.dispose();  // TODO add your handling code here:
  }//GEN-LAST:event_jToggleButton2ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    login log = new login();
    do {
      log.setVisible(true);
    } while 
            (login.konfirm());
            log.setVisible(true);
            new splash(5000);
            new frmUtama().setVisible(true);
  };
  
  public void doLogin(){
    String nama = tf1.getText();
    String pass = String.valueOf(tf2.getPassword());
    if(nama.equals(ID) && (pass).equals(Sandi)) {
      konfirmasi = true ;
    } else {
      JOptionPane.showMessageDialog(this, "Akses Ditolak", "Peringatan", JOptionPane.ERROR_MESSAGE);
    }
  }
  
  public static boolean konfirm(){
    return konfirmasi==false;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JTextField tf1;
  private javax.swing.JPasswordField tf2;
  // End of variables declaration//GEN-END:variables
}
